//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YardımEliWeb.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBilgilendirme
    {
        public int infoID { get; set; }
        public string infoGorsel { get; set; }
        public string infoBaslik { get; set; }
        public string infoAciklama { get; set; }
        public int userID { get; set; }
    }
}
