//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YardımEliWeb.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEsyaBagiscilari
    {
        public int esyaID { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Eposta { get; set; }
        public string BagisNesnesi { get; set; }
        public string Sehir { get; set; }
        public Nullable<int> TahminiDeger { get; set; }
        public int nakliyeId { get; set; }
    }
}
