//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YardımEliWeb.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHizmetler
    {
        public int hizmetID { get; set; }
        public string hizmetIcon { get; set; }
        public string hizmetBaslik { get; set; }
        public string hizmetAciklama { get; set; }
        public string hizmetYol { get; set; }
        public int userID { get; set; }
    }
}
