//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YardımEliWeb.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNakliyeciler
    {
        public int nakliyeId { get; set; }
        public string firmaAd { get; set; }
        public string firmaSehir { get; set; }
        public string firmaYetkiliAd { get; set; }
        public string firmaYetkiliSoyad { get; set; }
        public Nullable<int> kmBasinaUcret { get; set; }
        public string telefonNo { get; set; }
    }
}
